import turtle
from random import random

def random_color():
    return (random(),random(),random())

waffel = turtle.Turtle()

while True:
    waffel.pensize(7)
    waffel.color(random_color())
    waffel.forward(100)
    waffel.color(random_color())
    waffel.right(90)
    waffel.color(random_color())
    waffel.forward(100)
    waffel.color(random_color())
    waffel.right(90)
    waffel.color(random_color())
    waffel.forward(100)
    waffel.color(random_color())
    waffel.right(90)
    waffel.color(random_color())
    waffel.forward(100)
    waffel.color(random_color())
    waffel.left(120)
    waffel.color(random_color())
    waffel.forward(100)
    waffel.color(random_color())
    waffel.left(120) 
    waffel.color(random_color())
    waffel.forward(120)
    waffel.color(random_color())
    waffel.forward(100)
    waffel.color(random_color())
    waffel.left(90)
    waffel.color(random_color())
    waffel.forward(100)
    waffel.color(random_color())
    waffel.left(90)
    waffel.forward(100)
    waffel.color(random_color())
    waffel.forward(100)
    waffel.color(random_color())
    waffel.right(1000)
    waffel.color(random_color())
    waffel.forward(100)
    waffel.color(random_color())
    waffel.right(140)
    waffel.color(random_color())
    waffel.forward(100)
    waffel.right(90)
    waffel.forward(100)
    waffel.right(90)
    waffel.forward(100)
    waffel.right(90)
    waffel.forward(100)
    waffel.forward(100)
    waffel.forward(100)
    waffel.right(90)
    waffel.forward(100)
    waffel.right(90)
    waffel.forward(100)
    waffel.forward(100)
    waffel.right(90)
    waffel.forward(100)
    waffel.left(90)
    waffel.forward(100)
    waffel.right(90)
    waffel.forward(100)
    waffel.right(10)
